# Getting Started
First, you should create a folder for all of your related data to keep this organized throughout the project's completion.
#### **Now, you are ready to start coding!**
Create a new notebook on Google Colab to begin. To keep things simple for the sake of future code, lets import our data directly into the colab notebook. Colab immediatley looks into the "Content" folder for data when you are running codes. Make sure to click the file folder on the left side of the screen to view your folders. Click the three dots next to the content folder, then, press upload. Upload the CSV file for Public Health data, after downloading it [here.](https://uncch.instructure.com/courses/50015/files/6377514/download?download_frd=1)

The first step of the coding process is to import pandas and numpy as follows.

In [ ]:
import numpy as np
import pandas as pd

We'll also need to create our dataframe object, by using pandas to read in our .csv file. We can do this by running the following code. Make sure that the title in your code exactly matches the csv file you uploaded into your content folder.

In [ ]:
df=pd.read_csv("CountyHealthData_2014-2015.csv")

By typing "df", it shows our data frame in colab. Now, you are ready to create your subset!

In [ ]:
df

,State,Region,Division,County,FIPS,GEOID,SMS Region,Year,Premature death,Poor or fair health,...,Drug poisoning deaths,Uninsured adults,Uninsured children,Health care costs,Could not see doctor due to cost,Other primary care providers,Median household income,Children eligible for free lunch,Homicide rate,Inadequate social support
0,AK,West,Pacific,Aleutians West Census Area,2016,2016,Insuff Data,1/1/2014,NaN,0.122,...,NaN,0.374,0.250,3791.0,0.185,216.0,69192,0.127,NaN,0.287
1,AK,West,Pacific,Aleutians West Census Area,2016,2016,Insuff Data,1/1/2015,NaN,0.122,...,NaN,0.314,0.176,4837.0,0.185,254.0,74088,0.133,NaN,NaN
2,AK,West,Pacific,Anchorage Borough,2020,2020,Region 22,1/1/2014,6827.0,0.125,...,15.37,0.218,0.096,6588.0,0.119,135.0,71094,0.319,6.29,0.160
3,AK,West,Pacific,Anchorage Borough,2020,2020,Region 22,1/1/2015,6856.0,0.125,...,17.08,0.227,0.123,6582.0,0.119,148.0,76362,0.334,5.60,NaN
4,AK,West,Pacific,Bethel Census Area,2050,2050,Insuff Data,1/1/2014,13345.0,0.211,...,NaN,0.394,0.124,5860.0,0.200,169.0,41722,0.668,12.77,0.477
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6104,WY,West,Mountain,Uinta County,56041,56041,Insuff Data,1/1/2015,7436.0,0.135,...,18.66,0.192,0.090,7600.0,0.123,47.0,60953,0.273,NaN,NaN
6105,WY,West,Mountain,Washakie County,56043,56043,Insuff Data,1/1/2014,6580.0,0.106,...,NaN,0.225,0.086,8202.0,0.099,47.0,49533,0.328,NaN,0.133
6106,WY,West,Mountain,Washakie County,56043,56043,Insuff Data,1/1/2015,7572.0,0.106,...,NaN,0.226,0.101,7940.0,0.099,47.0,50740,0.309,NaN,NaN
6107,WY,West,Mountain,Weston County,56045,56045,Insuff Data,1/1/2014,5633.0,0.162,...,NaN,0.201,0.084,6906.0,0.130,28.0,53665,0.232,NaN,0.171
6108,WY,West,Mountain,Weston County,56045,56045,Insuff Data,1/1/2015,7819.0,0.162,...,NaN,0.189,0.092,7238.0,0.130,28.0,59314,0.235,NaN,NaN

# Creating Your First Subset
For this project, we are looking at the number of teen births in Arkansas. Now that we have imported our dataframe as df, we can begin filtering specific columns and rows. If we want to select multiple columns, we must list them in their own nested set of square brackets.

- In this case, the data for counties in Arizona is in rows 1-47. In addition, state, county and teen births are all seperate columns. We can filter them by using the following code.

In [ ]:
df[["State","County","Teen births"]][1:47]

   State                                       County  Teen births
1     AK                   Aleutians West Census Area         21.6
2     AK                            Anchorage Borough         37.7
3     AK                            Anchorage Borough         36.7
4     AK                           Bethel Census Area         80.3
5     AK                           Bethel Census Area         81.0
6     AK                       Dillingham Census Area         55.3
7     AK                       Dillingham Census Area         57.6
8     AK                 Fairbanks North Star Borough         38.1
9     AK                 Fairbanks North Star Borough         37.5
10    AK                               Haines Borough          NaN
11    AK                               Haines Borough          NaN
12    AK                               Juneau Borough         27.2
13    AK                               Juneau Borough         25.6
14    AK                      Kenai Peninsula Borough         30.2
15    AK                      Kenai Peninsula Borough         29.6
16    AK                    Ketchikan Gateway Borough         30.4
17    AK                    Ketchikan Gateway Borough         29.8
18    AK                        Kodiak Island Borough         32.2
19    AK                        Kodiak Island Borough         31.8
20    AK                   Lake and Peninsula Borough         52.0
21    AK                   Lake and Peninsula Borough         49.1
22    AK                    Matanuska-Susitna Borough         32.5
23    AK                    Matanuska-Susitna Borough         32.6
24    AK                             Nome Census Area         96.7
25    AK                             Nome Census Area         94.0
26    AK                          North Slope Borough        100.2
27    AK                          North Slope Borough         92.2
28    AK                     Northwest Arctic Borough         96.0
29    AK                     Northwest Arctic Borough         94.7
30    AK  Prince of Wales-Outer Ketchikan Census Area         50.5
31    AK  Prince of Wales-Outer Ketchikan Census Area         47.9
32    AK                                Sitka Borough         27.2
33    AK                                Sitka Borough         28.4
34    AK            Skagway-Hoonah-Angoon Census Area         28.5
35    AK            Skagway-Hoonah-Angoon Census Area         26.3
36    AK              Southeast Fairbanks Census Area         37.3
37    AK              Southeast Fairbanks Census Area         37.6
38    AK                   Valdez-Cordova Census Area         25.5
39    AK                   Valdez-Cordova Census Area         24.5
40    AK                     Wade Hampton Census Area        103.4
41    AK                     Wade Hampton Census Area        107.1
42    AK              Wrangell-Petersburg Census Area         33.0
43    AK              Wrangell-Petersburg Census Area         35.9
44    AK                    Yukon-Koyukuk Census Area         60.2
45    AK                    Yukon-Koyukuk Census Area         61.5
46    AL                               Autauga County         39.0

- Next, we are going to assign an easy-to-remember name to our subset. Let's call it "new_subset"

In [ ]:
new_subset=df[["State","County","Teen births"]][1:47]

Now, lets make sure our data appears correctly.

In [ ]:
new_subset

   State                                       County  Teen births
1     AK                   Aleutians West Census Area         21.6
2     AK                            Anchorage Borough         37.7
3     AK                            Anchorage Borough         36.7
4     AK                           Bethel Census Area         80.3
5     AK                           Bethel Census Area         81.0
6     AK                       Dillingham Census Area         55.3
7     AK                       Dillingham Census Area         57.6
8     AK                 Fairbanks North Star Borough         38.1
9     AK                 Fairbanks North Star Borough         37.5
10    AK                               Haines Borough          NaN
11    AK                               Haines Borough          NaN
12    AK                               Juneau Borough         27.2
13    AK                               Juneau Borough         25.6
14    AK                      Kenai Peninsula Borough         30.2
15    AK                      Kenai Peninsula Borough         29.6
16    AK                    Ketchikan Gateway Borough         30.4
17    AK                    Ketchikan Gateway Borough         29.8
18    AK                        Kodiak Island Borough         32.2
19    AK                        Kodiak Island Borough         31.8
20    AK                   Lake and Peninsula Borough         52.0
21    AK                   Lake and Peninsula Borough         49.1
22    AK                    Matanuska-Susitna Borough         32.5
23    AK                    Matanuska-Susitna Borough         32.6
24    AK                             Nome Census Area         96.7
25    AK                             Nome Census Area         94.0
26    AK                          North Slope Borough        100.2
27    AK                          North Slope Borough         92.2
28    AK                     Northwest Arctic Borough         96.0
29    AK                     Northwest Arctic Borough         94.7
30    AK  Prince of Wales-Outer Ketchikan Census Area         50.5
31    AK  Prince of Wales-Outer Ketchikan Census Area         47.9
32    AK                                Sitka Borough         27.2
33    AK                                Sitka Borough         28.4
34    AK            Skagway-Hoonah-Angoon Census Area         28.5
35    AK            Skagway-Hoonah-Angoon Census Area         26.3
36    AK              Southeast Fairbanks Census Area         37.3
37    AK              Southeast Fairbanks Census Area         37.6
38    AK                   Valdez-Cordova Census Area         25.5
39    AK                   Valdez-Cordova Census Area         24.5
40    AK                     Wade Hampton Census Area        103.4
41    AK                     Wade Hampton Census Area        107.1
42    AK              Wrangell-Petersburg Census Area         33.0
43    AK              Wrangell-Petersburg Census Area         35.9
44    AK                    Yukon-Koyukuk Census Area         60.2
45    AK                    Yukon-Koyukuk Census Area         61.5
46    AL                               Autauga County         39.0

If this works, you should see the same dataset you saw when running the original code in step one.

Now that we have created our subset, we are ready to export!

# Exporting Your Subset

In order to export our subset we need to use the .to_csv() method.

The name of the file goes in parenthesis along with index=False in order to avoid the addition of an unneeded row of indices that Pandas adds. We are also going to choose a name for our new subset. Mine is going to be, "Teen_Births_in_Arkansas.csv"

With all of this together, we should have the following code.

In [ ]:
new_subset.to_csv("Teen_Births_in_Arkansas.csv",index=False)

The subset should show up in your content folder, which you can then download and add to the folder you created earlier for storing all the project related files.

## Congrats, you just made your first subset!!

# Getting Started
First, you should create a folder for all of your related data to keep this organized throughout the project's completion.
#### **Now, you are ready to start coding!**
Create a new notebook on Google Colab to begin. To keep things simple for the sake of future code, lets import our data directly into the colab notebook. Colab immediatley looks into the "Content" folder for data when you are running codes. Make sure to click the file folder on the left side of the screen to view your folders. Click the three dots next to the content folder, then, press upload. Upload the CSV file for Public Health data, after downloading it [here.](https://uncch.instructure.com/courses/50015/files/6377514/download?download_frd=1)

The first step of the coding process is to import pandas and numpy as follows.

        import numpy as np
        import pandas as pd
We'll also need to create our dataframe object, by using pandas to read in our .csv file. We can do this by running the following code. Make sure that the title in your code exactly matches the csv file you uploaded into your content folder.

        df=pd.read_csv("CountyHealthData_2014-2015.csv")
        df
By typing "df", it shows our data frame in colab. Now, you are ready to create your subset!

# Creating Your First Subset
For this project, we are looking at the number of teen births in Arkansas. Now that we have imported our dataframe as df, we can begin filtering specific columns and rows. If we want to select multiple columns, we must list them in their own nested set of square brackets.

- In this case, the data for counties in Arizona is in rows 1-47. In addition, state and teen births are two seperate columns. We can filter them by using the following code.

        df[["State","County","Teen births"]][1:47]
        
- Next, we are going to assign an easy-to-remember name to our subset. Let's call it "new_subset"
        
        new_subset=df[["State","County","Teen births"]][1:47]
Now, lets make sure our data appears correctly.

        new_subset
If this works, you should see the same dataset you saw when running the original code in step one.

Now that we have created our subset, we are ready to export!

# Exporting Your Subset

In order to export our subset we need to use the .to_csv() method.

The name of the file goes in parenthesis along with index=False in order to avoid the addition of an unneeded row of indices that Pandas adds. We are also going to choose a name for our new subset. Mine is going to be, "Teen_Births_in_Arkansas.csv"

With all of this together, we should have the following code.

        new_subset.to_csv("Teen_Births_in_Arkansas.csv",index=False)
        
The subset should show up in your content folder, which you can then download and add to the folder you created earlier for storing all the project related files.

## Congrats, you just made your first subset!!